### ISSUE TITLE
Typo: Entiites --> Entities

### ISSUE THREAD

**Issue by eforgacs** [noizu/domain-objects#1]
"Entities" is misspelled in the titles as "Entiites".

**Comment by noizu** [comment]
Heh Dyslexia is a hell of a drug. I'm sure there are plenty more typos than that.

**Comment by eforgacs** [comment]
Hah. Happy to help out where I can. :)

**Comment by noizu** [comment]
All my recent stuff is in elixir these days. I'm not convinced this one still runs although theoretically greatnonprofits should still have dependencies on it in their api layer.
